DROP TABLE IF EXISTS users;

CREATE TABLE users (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL,
email TEXT NOT NULL
);

DROP TABLE IF EXISTS pets;

CREATE TABLE pets (
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER NOT NULL,
pet_type INTEGER NOT NULL,
pet_name TEXT,
description TEXT 
);
